project: 
  type: website
  output-dir: docs

website: 
  title: Technologie kwantowe
  sidebar:
    style: "docked" 
    contents:
      - index.qmd
      - section : "Wykłady"
        contents:
          - lectures/wyklad1.qmd

  navbar:
    left:
          - href: ksiazki.qmd
            text: Książki
        
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true